[package]
name = "rust-web-server"
version = "0.1.0"
edition = "2021"

[lib]
name = "server"
path = "src/server/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
